export type Type = 
  | 'normal' | 'fire' | 'water' | 'electric' | 'grass' | 'ice' // 6개
  | 'fighting' | 'poison' | 'ground' | 'flying' | 'psychic' // 5개
  | 'bug' | 'rock' | 'ghost' | 'dragon' | 'dark' | 'steel' | 'fairy' | string; // 7개

  export const typeColor: Record<string, string> = {
    '노말': "#9fa19f",
    '불꽃': "#c60013",
    '물': "#0067d2",
    '전기': "#9a6c00",
    '풀': "#1c8605",
    '얼음': "#007ea3",
    '격투': "#ff8000",
    '독': "#9141cb",
    '땅': "#915121",
    '비행': "#81b9ef",
    '에스퍼': "#d01960",
    '벌레': "#6b7d00",
    '바위': "#afa981",
    '고스트': "#704170",
    '드래곤': "#2d48c4",
    '악': "#392b29",
    '강철': "#3c7f95",
    '페어리': "#bd3fbf",
  };

export const typeTranslation: Record<string, string> = {
  normal: '노말',
  fire: '불꽃',
  water: '물',
  electric: '전기',
  grass: '풀',
  ice: '얼음',
  fighting: '격투',
  poison: '독',
  ground: '땅',
  flying: '비행',
  psychic: '에스퍼',
  bug: '벌레',
  rock: '바위',
  ghost: '고스트',
  dragon: '드래곤',
  dark: '악',
  steel: '강철',
  fairy: '페어리'
};

// 타입 상성 테이블 정의
export const typeChart: Record<Type, Record<Type, number>> = {
  normal: {
    fighting: 2, ghost: 1,
    normal: 1, fire: 1, water: 1, electric: 1, grass: 1, ice: 1, poison: 1, ground: 1, flying: 1, psychic: 1, bug: 1, rock: 1, dragon: 1, dark: 1, steel: 1, fairy: 1
  },
  fire: {
    fire: 0.5, water: 2, grass: 0.5, bug: 0.5, rock: 2, dragon: 1, steel: 0.5,
    normal: 1,
    electric: 1,
    ice: 0.5,
    fighting: 1,
    poison: 1,
    ground: 2,
    flying: 1,
    psychic: 1,
    ghost: 1,
    dark: 1,
    fairy: 0.5
  },
  water: {
    fire: 0.5, water: 0.5, grass: 2, electric: 2,
    normal: 1,
    ice: 0.5,
    fighting: 1,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 0.5,
    fairy: 0
  },
  electric: {
    electric: 0.5, ground: 2,
    normal: 1,
    fire: 1,
    water: 1,
    grass: 1,
    ice: 1,
    fighting: 1,
    poison: 1,
    flying: 0.5,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 0.5,
    fairy: 1
  },
  grass: {
    fire: 2, water: 0.5, electric: 0.5, grass: 0.5, poison: 2, bug: 2, flying: 2, dragon: 1, steel: 1,
    normal: 1,
    ice: 2,
    fighting: 1,
    ground: 1,
    psychic: 1,
    rock: 1,
    ghost: 1,
    dark: 1,
    fairy: 1
  },
  ice: {
    fire: 2, water: 1, ice: 0.5, steel: 2,
    normal: 1,
    electric: 1,
    grass: 1,
    fighting: 1,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 2,
    ghost: 1,
    dragon: 1,
    dark: 1,
    fairy: 0
  },
  fighting: {
    fighting: 1, flying: 2, psychic: 2, ghost: 1,
    normal: 1,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    poison: 1,
    ground: 1,
    bug: 0.5,
    rock: 0.5,
    dragon: 1,
    dark: 0.5,
    steel: 1,
    fairy: 2
  },
  poison: {
    poison: 0.5, ground: 2, psychic: 2,
    normal: 1,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 0.5,
    ice: 1,
    fighting: 0.5,
    flying: 1,
    bug: 0.5,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 0.5
  },
  ground: {
    fire: 1, electric: 0, grass: 2, ice: 2, water: 2, poison: 0.5, flying: 1,
    normal: 1,
    fighting: 1,
    ground: 1,
    psychic: 1,
    bug: 1,
    rock: 0.5,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1
  },
  flying: {
    electric: 2, rock: 2, ice: 2,
    normal: 1,
    fire: 1,
    water: 1,
    grass: 1,
    fighting: 1,
    poison: 1,
    ground: 0,
    flying: 1,
    psychic: 1,
    bug: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1
  },
  psychic: {
    fighting: 0.5, psychic: 0.5, ghost: 2,
    normal: 1,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    poison: 1,
    ground: 1,
    flying: 1,
    bug: 2,
    rock: 1,
    dragon: 1,
    dark: 2,
    steel: 1,
    fairy: 1
  },
  bug: {
    fire: 2, grass: 0.5, flying: 2, ghost: 1,
    normal: 1,
    water: 1,
    electric: 1,
    ice: 1,
    fighting: 0.5,
    poison: 1,
    ground: 0.5,
    psychic: 1,
    bug: 1,
    rock: 2,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1
  },
  rock: {
    fire: 0.5, water: 2, grass: 2, steel: 2, fighting: 2, ground: 2, flying: 0.5,
    normal: 0.5,
    electric: 1,
    ice: 1,
    poison: 0.5,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    fairy: 1
  },
  ghost: {
    ghost: 2, dark: 2, fighting: 0,
    normal: 0,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    poison: 0.5,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 0.5,
    rock: 1,
    dragon: 1,
    steel: 1,
    fairy: 1
  },
  dragon: {
    dragon: 2, steel: 1, fairy: 2,
    normal: 1,
    fire: 0.5,
    water: 0.5,
    electric: 0.5,
    grass: 0.5,
    ice: 2,
    fighting: 1,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dark: 1
  },
  dark: {
    psychic: 0, ghost: 0.5, fairy: 2,
    normal: 1,
    fire: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    fighting: 2,
    poison: 1,
    ground: 1,
    flying: 1,
    bug: 2,
    rock: 1,
    dragon: 1,
    dark: 0.5,
    steel: 1
  },
  steel: {
    fire: 2, electric: 1, steel: 0.5, rock: 0.5, fairy: 0.5,
    normal: 0.5,
    water: 1,
    grass: 0.5,
    ice: 0.5,
    fighting: 2,
    poison: 0,
    ground: 2,
    flying: 0.5,
    psychic: 0.5,
    bug: 0.5,
    ghost: 1,
    dragon: 0.5,
    dark: 1
  },
  fairy: {
    fire: 1, poison: 2, steel: 2, dark: 0.5, fighting: 0.5,
    normal: 1,
    water: 1,
    electric: 1,
    grass: 1,
    ice: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 0.5,
    rock: 1,
    ghost: 1,
    dragon: 0,
    fairy: 1
  }
};