export const POCHAMS_POKEMON_DATA = [
  'Abomasnow',
  'Absol',
  'Aegislash Shield Forme',
  'Aerodactyl',
  'Aggron',
  'Alakazam',
  'Alcremie',
  'Alolan Ninetales',
  'Alolan Raichu',
  'Altaria',
  'Ampharos',
  'Annihilape',
  'Appletun',
  'Araquanid',
  'Arbok',
  'Arcanine',
  'Archaludon',
  'Ariados',
  'Armarouge',
  'Aromatisse',
  'Audino',
  'Aurorus',
  'Avalugg',
  'Azumarill',
  'Banette',
  'Barbaracle',
  'Basculegion Female',
  'Basculegion Male',
  'Bastiodon',
  'Beartic',
  'Beedrill',
  'Bellibolt',
  'Blastoise',
  'Blaziken',
  'Camerupt',
  'Castform',
  'Ceruledge',
  'Chandelure',
  'Charizard',
  'Chesnaught',
  'Chimecho',
  'Clawitzer',
  'Clefable',
  'Cofagrigus',
  'Conkeldurr',
  'Corviknight',
  'Crabominable',
  'Decidueye',
  'Dedenne',
  'Delphox',
  'Diggersby',
  'Ditto',
  'Dragalge',
  'Dragapult',
  'Dragonite',
  'Drampa',
  'Eelektross',
  'Emboar',
  'Emolga',
  'Empoleon',
  'Espathra',
  'Espeon',
  'Excadrill',
  'Falinks',
  'Farigiraf',
  'Feraligatr',
  'Flapple',
  'Flareon',
  'Floette',
  'Florges Red Flower',
  'Forretress',
  'Froslass',
  'Furfrou Natural Form',
  'Galarian Slowbro',
  'Galarian Slowking',
  'Galarian Stunfisk',
  'Gallade',
  'Garbodor',
  'Garchomp',
  'Gardevoir',
  'Garganacl',
  'Gengar',
  'Gholdengo',
  'Glaceon',
  'Glalie',
  'Glimmora',
  'Gliscor',
  'Golurk',
  'Goodra',
  'Gourgeist Jumbo Variety',
  'Gourgeist Large Variety',
  'Gourgeist Small Variety',
  'Gourgeist',
  'Greninja',
  'Grimmsnarl',
  'Gyarados',
  'Hatterene',
  'Hawlucha',
  'Heliolisk',
  'Heracross',
  'Hippowdon',
  'Hisuian Arcanine',
  'Hisuian Avalugg',
  'Hisuian Decidueye',
  'Hisuian Goodra',
  'Hisuian Samurott',
  'Hisuian Typhlosion',
  'Hisuian Zoroark',
  'Houndoom',
  'Houndstone',
  'Hydrapple',
  'Hydreigon',
  'Incineroar',
  'Infernape',
  'Jolteon',
  'Kangaskhan',
  'Kingambit',
  'Kleavor',
  'Klefki',
  'Kommo-o',
  'Krookodile',
  'Leafeon',
  'Liepard',
  'Lopunny',
  'Lucario',
  'Luxray',
  'Lycanroc Dusk Form',
  'Lycanroc Midnight Form',
  'Lycanroc',
  'Machamp',
  'Malamar',
  'Mamoswine',
  'Manectric',
  'Maushold',
  'Mawile',
  'Medicham',
  'Meganium',
  'Meowscarada',
  'Meowstic Female',
  'Meowstic',
  'Metagross',
  'Milotic',
  'Mimikyu',
  'Morpeko',
  'Mr. Rime',
  'Mudsdale',
  'Musharna',
  'Ninetales',
  'Noivern',
  'Oranguru',
  'Orthworm',
  'Overqwil',
  'Palafin Zero Form',
  'Paldean Tauros Aqua Breed',
  'Paldean Tauros Blaze Breed',
  'Paldean Tauros Combat Breed',
  'Pangoro',
  'Passimian',
  'Pelipper',
  'Pidgeot',
  'Pikachu',
  'Pinsir',
  'Politoed',
  'Polteageist',
  'Primarina',
  'Pyroar',
  'Quaquaval',
  'Qwilfish',
  'Raichu',
  'Rampardos',
  'Reuniclus',
  'Rhyperior',
  'Roserade',
  'Rotom Fan',
  'Rotom Frost',
  'Rotom Heat',
  'Rotom Mow',
  'Rotom Wash',
  'Rotom',
  'Runerigus',
  'Sableye',
  'Salazzle',
  'Samurott',
  'Sandaconda',
  'Sceptile',
  'Scizor',
  'Scolipede',
  'Scovillain',
  'Scrafty',
  'Serperior',
  'Sharpedo',
  'Simipour',
  'Simisage',
  'Simisear',
  'Sinistcha',
  'Skarmory',
  'Skeledirge',
  'Slowbro',
  'Slowking',
  'Slurpuff',
  'Sneasler',
  'Snorlax',
  'Spiritomb',
  'Staraptor',
  'Starmie',
  'Steelix',
  'Stunfisk',
  'Swampert',
  'Sylveon',
  'Talonflame',
  'Tauros',
  'Tinkaton',
  'Torkoal',
  'Torterra',
  'Toucannon',
  'Toxapex',
  'Toxicroak',
  'Trevenant',
  'Tsareena',
  'Typhlosion',
  'Tyranitar',
  'Tyrantrum',
  'Umbreon',
  'Vanilluxe',
  'Vaporeon',
  'Venusaur',
  'Victreebel',
  'Vileplume',
  'Vivillon Fancy Pattern',
  'Volcarona',
  'Watchog',
  'Weavile',
  'Whimsicott',
  'Wyrdeer',
  'Zoroark',
] as const;

export type PochamsPokemonDataName = (typeof POCHAMS_POKEMON_DATA)[number];
