import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav/Nav";
import FloatingBtn from "@/components/floatingBtn/FloatingBtn";
import { TeamSessionBootstrap } from "@/components/team/TeamSessionBootstrap";
import s from './main.module.scss'
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="" suppressHydrationWarning>
        <TeamSessionBootstrap />
        <div className={s.main}>
          <Nav />
          {children}
          <FloatingBtn />
        </div>
        <Footer />
        <div id="modal" />
      </body>
    </html>
  );
}
